### ISSUE TITLE
yamz redirect fail

### ISSUE THREAD

**Issue by mariagould** [CDLUC3/n2t-admin#7]
On Friday 1/13 we received an error message that the YAMZ redirect test in N2T had failed. We need to investigate why this is failing and how to resolve it. 

> not ok 5 - YAMZ target redirects
> # Failed test 'YAMZ target redirects'
> # at t/egn_post_install_n2t.t line 166.
> # ' minter|binder=99999/fk4|ezid user=ezid host=localhost:18443
> # Location: https://yamz.net/ark:/99152/h1023
> # '
> # doesn't match '(?^m:^Location: https://yamz.net/term=h1023$)'

**Comment by jkunze** [comment]
Just seeing this, I'd forgotten that I'd set up an explicit test for the redirect.
It's failing because I updated the redirect rule from the "Shoulders for shared NAANs" file (maintained by the ARKA NAAN WG). 
The new redirect rule is working correctly, but the test in egn_post_install_n2t.t is now testing for the wrong condition.

Since the Yamz redirect is now working in a much more mainstream fashion, the fix I'd recommend is just removing this test.
